### PR TITLE
Speed up export handling in magic.js

### PR DESCRIPTION
**Pull request by HaGuesto**
The export of large data is now down to a delay of a few seconds only and in the acceptable range.

The reason for the time delay was the creation of a collection called `allTargets` which is not used for exporting and the unselecting of all items in the list.

### CODE REVIEW

**Comment by HaGuesto** [comment]
[Performance issue when exporting boxes - page becomes unresponsive. #medium](https://trello.com/c/GTKFBAjD/317-performance-issue-when-exporting-boxes-page-becomes-unresponsive-medium)

**Comment by HaGuesto** [comment]
@DurkoMatko @jamescrowley When you have the time, it would be nice to get a review for this.

**Comment by DurkoMatko** [comment]
@HaGuesto ok I've compared the performance even with just 350 boxes and it indeed feels bit more swift even with such small numbers! Nice :)

**Comment by HaGuesto** [comment]
@DurkoMatko Thanks!

**Pull request merged**
