### PR TITLE
Validate qr_id when box is created on mobile

### PR DESCRIPTION
**Pull request by HaGuesto**
This is a minimal solution. I just validated with an if statement if `$_POST['qr_id']` is set and not zero when the box form is submitted on mobile phones. 

Trello card
--------
https://trello.com/c/nHdAMVbi

### CODE REVIEW

**Comment by jamescrowley** [comment]
@HaGuesto it was this bit in the existing code that didn't make sense to me?

         if(!intval($_POST['box_id'])) {
		$new = true;
		do {
			$_POST['box_id'] = generateBoxID();
			} while(db_value('SELECT COUNT(id) FROM stock WHERE box_id = :box_id',array('box_id'=>$_POST['box_id'])));
		}

do you know what that's doing? I'd have thought if there was no POST box_id then we should stop then and there, no?

**Comment by HaGuesto** [comment]
> @HaGuesto it was this bit in the existing code that didn't make sense to me?
> 
> ```
>      if(!intval($_POST['box_id'])) {
> 	$new = true;
> 	do {
> 		$_POST['box_id'] = generateBoxID();
> 		} while(db_value('SELECT COUNT(id) FROM stock WHERE box_id = :box_id',array('box_id'=>$_POST['box_id'])));
> 	}
> ```
> 
> do you know what that's doing? I'd have thought if there was no POST box_id then we should stop then and there, no?

`box_id` is the 6-digit unique number for the box which is different to the `qr_id` which is the id of the qr-hash in the `qr`-db-table.

If a qr-code is scanned which has no box connected to it (a new fresh qr-code) then this if clause is true and generates a random `box_id`.

**Comment by HaGuesto** [comment]
@jamescrowley

**Comment by HaGuesto** [comment]
@jamescrowley updated

**Pull request merged**
