### PR TITLE
Fix: valid mobile organisation selector request URI

### PR DESCRIPTION
**Pull request by DurkoMatko**
**fix:** mobile organisation selector request URI

(I guess only boxwise gods get to select organisation right? So noone probably noticed this as we don't use mobile :D)

### CODE REVIEW

**Comment by DurkoMatko** [comment]
@jamescrowley I've did my best to try to create such scenario but couldn't get it. It seems it's always the first query parameter. I guess it wasn't in the past?

**Comment by jamescrowley** [comment]
I think scanning a box could trigger this, no? 

https://staging.boxwise.co/mobile.php?barcode=abc

**Comment by jamescrowley** [comment]
I think it would be safer to just make the template handle both, in case it changes again in future.

**Comment by DurkoMatko** [comment]
@jamescrowley Done.

**Comment by jamescrowley** [comment]
Thanks @durkomatko, much appreciated :)

**Pull request merged**
