### PR TITLE
Bug Fix: Addressing Misalignment Issue with HTML Field Titles

### PR DESCRIPTION
**Pull request by vahidbazzaz**
This PR addresses a minor alignment issue affecting the HTML field title in certain screen sizes.

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[Dropapp Bug: #tiny "About Locations" title in "Edit Warehouses" page is misaligned](https://trello.com/c/bQhMFCo4/1330-dropapp-bug-tiny-about-locations-title-in-edit-warehouses-page-is-misaligned)

**Comment by aerinsol** [comment]
Since this is a one line change @vahidbazzaz , I'm going to merge and check it on staging.

**Comment by aerinsol** [comment]
hmm, this is still not fixed on staging @vahidbazzaz and there doesn't seem to be any problem with the deploy.

**Comment by aerinsol** [comment]
It was the snapshots being full issue, @HaGuesto fixed it 😁

**Pull request merged**
