### PR TITLE
Second Password Validation and Strength Test

### PR DESCRIPTION
**Pull request by vahidbazzaz**
The following is done:

- [X] Resolved the second password validation
- [X] Test strength of password (it can consist of alphanumerals characters and special character (such as `!@#$%^&*-_=+) and should has minimum of 12 characters lenght includes at least a letter and 2 symbol or numbers)
- [X] Added checkPassword method in tools.php to compare password with second password and checking the strength
- [X] Added custom validation rule in magic.js to validate password strength
- [X] Modified version of magic.js in query string in the cms_footer.php to force browser to update JS cache

### CODE REVIEW

**Comment by aerinsol** [comment]
I'd like to increase the length to 12 and remove the upper/lowercase
requirement, and instead require use of at least 2 symbol or numbers

**Comment by aerinsol** [comment]
See:
https://www.lmgsecurity.com/how-long-should-your-password-be-a-technical-guide-to-a-safe-password-length-policy/

As recent improvements in computing power make 8 character passwords
insufficient.

**Comment by vahidbazzaz** [comment]
@aerinsol I just updated the password strength requirements per your suggestion. Per Auth0 password strength requirement also at least one alphabet  is needed, so I require that as well.

**Review by aerinsol — CHANGES_REQUESTED** [review]
update comment to match 12 char requirement

**Review by aerinsol — CHANGES_REQUESTED** [review]
typo "length"

**Review by aerinsol — CHANGES_REQUESTED** [review]
typo should be "symbols"

**Review by aerinsol — CHANGES_REQUESTED** [review]
Can we separate out the error to the two different use cases, so the user knows which behavior to correct:

1) The password does not match with your previously confirmed password
AND
2) Your password must be at least 12 characters long and include a letter and two symbols or numbers.

**Review by aerinsol — CHANGES_REQUESTED** [review]
request correction to "should be a minimum length of 12 characters, including a letter and two symbols or numbers"

**Comment by vahidbazzaz** [comment]
> Can we separate out the error to the two different use cases, so the user knows which behavior to correct:
> 
> 1. The password does not match with your previously confirmed password
>    AND
> 2. Your password must be at least 12 characters long and include a letter and two symbols or numbers.

Sure, actually its currently work like what you are suggesting; when a user typing any character on the password input, one validator checking if the password is strong enough and likewise when user typing in the confirm password input, it shown error if its not the same as the password.

**Comment by vahidbazzaz** [comment]
> request correction to "should be a minimum length of 12 characters, including a letter and two symbols or numbers"

@aerinsol I think we need to use at least one uppercase and lowercase as Auth0 does not accept common password as well, please check this and then we can finalize the password requirements [https://auth0.com/docs/connections/database/password-strength](url)

**Comment by aerinsol** [comment]
@vahidbazzaz that's the default for the admins dashboard, you mean. I'd prefer to specify the combination of special characters to match:

> Good: at least 8 characters including at least 3 of the following 4 types of characters: a lower-case letter, an upper-case letter, a number, a special character (such as !@#$%^&*).

While keeping it at 12 characters.

**Review by aerinsol — CHANGES_REQUESTED** [review]
We should match the profile password error with the password hints for password creation so we can keep them in sync. 

We can use the same one as done in password creation or simply unify them as a string in a variable, whichever makes the most sense.

**Comment by vahidbazzaz** [comment]
> We should match the profile password error with the password hints for password creation so we can keep them in sync.
> 
> We can use the same one as done in password creation or simply unify them as a string in a variable, whichever makes the most sense.

@aerinsol I think the first suggestion can be done as using the variables in JS can't be done in current setting. Also we you please let me know if the following message is okay to be set for both JS  and backend validation error:

> Your password must be at least 12 characters including at least 3 of the following 4 types of characters: a lowercase letter, an uppercase letter, a number, a special character (such as !@#$%&/=?_.,:;-).

**Comment by aerinsol** [comment]
@vahidbazzaz looks good!

**Review by aerinsol — APPROVED** [review]

**Review by HaGuesto — APPROVED** [review]
## Code Review

The code looks super clean. Very well done. No complaints at all, @Vahid.
Quite a mastery of regular expressions.

## Functional Review
No problems encountered at all.

**Pull request merged**
