### PR TITLE
Create a temporary endpoint for experiment keep-alive of GCloud instance

### PR DESCRIPTION
**Pull request by vahidbazzaz**
The purpose of this PR is to create an endpoint that can be used for @johnsmol's experiment to be able to keep the gcloud instance running.

### CODE REVIEW

**Comment by vahidbazzaz** [comment]
[BUG: Forms cannot be submitted when opened for too long](https://trello.com/c/KGuRajmt)

**Comment by aerinsol** [comment]
Lets check there's no interaction with this other issue around submissions first https://trello.com/c/VWRgAeeS

**Review by HaGuesto — APPROVED** [review]

**Comment by HaGuesto** [comment]
from my side we can merge this since it is not connected to any other functionality @aerinsol

**Comment by HaGuesto** [comment]
[Exploratory Research on how to work around Google Cloud Platform's down time issue](https://trello.com/c/2KZKzJpq/889-exploratory-research-on-how-to-work-around-google-cloud-platforms-down-time-issue)

**Pull request merged**
