### PR TITLE
Add DB migration to insert InTransit box state

### PR DESCRIPTION
**Pull request by pylipp**

### CODE REVIEW

**Comment by pylipp** [comment]
[2.0 Make Logical Managment of BoxView and Shipments consistent](https://trello.com/c/U9qrVxle/1196-20-make-logical-managment-of-boxview-and-shipments-consistent)

**Comment by pylipp** [comment]
[2.0 Add InTransit box state](https://trello.com/c/LMh0zJhQ/1224-20-add-intransit-box-state)

**Review by HaGuesto — APPROVED** [review]
code and functional review passed. Thanks @pylipp

**Comment by pylipp** [comment]
The workflow that was run on the [merge commit](https://github.com/boxwise/dropapp/runs/14341825730) did not succeed, not sure if the migration was effective @HaGuesto

**Comment by pylipp** [comment]
[DB migration for InTransit box state](https://trello.com/c/ZRBOVdG8/1227-db-migration-for-intransit-box-state)

**Pull request merged**
