### PR TITLE
Add toast notifications to mobile (former "Replace nofilter flags with safer solution")

### PR DESCRIPTION
**Pull request by DurkoMatko**
**change**: replace all mobile notifications (DOM elements from smarty templates) by noty toast notifications (showing smarty DOM notification is still possible by passing message GET parameter)
**change**: adjusted cypress moibile tests to expect toast notifications

### CODE REVIEW

**Comment by DurkoMatko** [comment]
[Not escape html in savebox on mobile](https://trello.com/c/J44LwGJ6/383-not-escape-html-in-savebox-on-mobile)

**Comment by DurkoMatko** [comment]
[Not escape html in barcode.php](https://trello.com/c/pydMp0zb/382-not-escape-html-in-barcodephp)

**Comment by jamescrowley** [comment]
@DurkoMatko how do you feel about this having tried the approach? I'm a little concerned I've nudged you in a direction that doesn't seem that nice now that I look at it, because of the number of random parameters you have to scatter all over the place.

**Comment by DurkoMatko** [comment]
@jamescrowley It felt like making something work what's not supposed to be there 😄  We can do notifications by creating templates for notifications if this is something we don't want. And potentially hide/remove those DOM elements by some JS timer, so they act bit more like notifications. It's a pity that I've spent time on this but yeah, whatever..If it's not good, it's not good :D

**Comment by HaGuesto** [comment]
closing due to redesign of corresponding task https://trello.com/c/PcDxAcMq

**Pull request closed without merging**
