### PR TITLE
Boxid qr unique constraints

### PR DESCRIPTION
**Pull request by cohenlea**

### CODE REVIEW

**Comment by cohenlea** [comment]
[Implement unique constraint for box_id in stock table #tiny](https://trello.com/c/MHlRZR3I/348-implement-unique-constraint-for-boxid-in-stock-table-tiny)

**Comment by cohenlea** [comment]
[Implement unique constraint for hash-legacy-combination in qr-db-table #small](https://trello.com/c/KEtU8lbK/349-implement-unique-constraint-for-hash-legacy-combination-in-qr-db-table-small)

**Comment by HaGuesto** [comment]
@cohenlea might it possible that you based your branch on top of #251 
In this case it is not a biggie, but please base your branches only on master if possible.

**Comment by cohenlea** [comment]
@HaGuesto @jamescrowley I tried to rebase and things got messy - I'm going to close this one and make a new branch so it's cleaner

**Pull request closed without merging**
