### PR TITLE
Add unique Constraint for qr_id in stock table

### PR DESCRIPTION
**Pull request by HaGuesto**

### CODE REVIEW

**Comment by HaGuesto** [comment]
[Duplicate qr_ids in stock db-table](https://trello.com/c/e4YxFzPw/473-duplicate-qrids-in-stock-db-table)

**Comment by HaGuesto** [comment]
[Duplicate qr_ids in stock db-table](https://trello.com/c/e4YxFzPw/473-duplicate-qrids-in-stock-db-table)

**Comment by aerinsol** [comment]
@HaGuesto is this still required? Who do you want to review this?

**Comment by HaGuesto** [comment]
@aerinsol I have not done this step yet:

> @hanspetergurtner1 will destroy the QR code duplicates and then send email to organizations informing them the labels need to be reprinted. @hanspetergurtner1 will send email to @roannak for review.

Therefore, nothing to review yet

**Comment by aerinsol** [comment]
@HaGuesto this is not merged?

**Comment by HaGuesto** [comment]
before I merge it I have to do quite a bit of research in the db and inform the users of duplicate qr-codes and which boxes are connected to it.
That takes quite a bit of time. Since it does not cost us any errors atm there was no priority for me to resolve this.

But yes you are right. It should not be staing open for such a long time.

**Pull request merged**
