### PR TITLE
Fix for the Stockroom Issue

### PR DESCRIPTION
**Pull request by vahidbazzaz**
In this PR, the issue in the stockroom query has been fixed.

Related PR: https://github.com/boxwise/dropapp/pull/501

### CODE REVIEW

**Comment by HaGuesto** [comment]
@vahidbazzaz can u link the ticket or at least the connected sentry error code to this PR?

**Comment by vahidbazzaz** [comment]
Ref. Sentry: https://sentry.io/share/issue/6e74ee137def4d08be3ec157c411b0e4/

**Review by HaGuesto — APPROVED** [review]
@vahidbazzaz please create a trello ticket in the merged to master list and link the sentry issue in it

**Comment by vahidbazzaz** [comment]
[Fix for the Stockroom Issue](https://trello.com/c/7bfLqXcJ)

**Pull request merged**
