### PR TITLE
added deleted column to locations table

### PR DESCRIPTION
**Pull request by HaGuesto**

### CODE REVIEW

**Comment by HaGuesto** [comment]
[Add delete - column to locations table.](https://trello.com/c/GbWDZ27Z/316-add-delete-column-to-locations-table)

**Comment by DurkoMatko** [comment]
[Cypress: User Mgmt. 2.5 and 2.5.1 through 2.5.4 #medium](https://trello.com/c/ob224hjc/341-cypress-user-mgmt-25-and-251-through-254-medium)

**Comment by HaGuesto** [comment]
>  [Cypress: User Mgmt. 2.5 and 2.5.1 through 2.5.4 #medium](https://trello.com/c/ob224hjc/341-cypress-user-mgmt-25-and-251-through-254-medium)

You connected to the wrong PR :)

**Comment by DurkoMatko** [comment]
@HaGuesto it was a misclick while connecting the PR :D thought the comment with trello link will get deleted when I change the selected PR..deleting it now

**Pull request merged**
